// <auto-generated />
using System;
using FutbolYa.WebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutbolYa.WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251118012323_AddEmailConfirmationToUsuario")]
    partial class AddEmailConfirmationToUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvaluadoId")
                        .HasColumnType("int");

                    b.Property<int>("EvaluadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvaluadoId");

                    b.HasIndex("EvaluadorId");

                    b.HasIndex("PartidoId");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("FutbolYa.WebAPI.Models.Cancha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Superficie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEstablecimientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioEstablecimientoId");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("FutbolYa.WebAPI.Models.DatosTarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FechaExpiracion")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashCvv")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("HashNumero")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("HashToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NombreTitular")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.Property<string>("Ultimos4")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId");

                    b.ToTable("DatosTarjetas");
                });

            modelBuilder.Entity("FutbolYa.WebAPI.Models.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("FutbolYa.WebAPI.Models.PartidoUsuario", b =>
                {
                    b.Property<int>("PartidosId")
                        .HasColumnType("int");

                    b.Property<int>("JugadoresId")
                        .HasColumnType("int");

                    b.HasKey("PartidosId", "JugadoresId");

                    b.HasIndex("JugadoresId");

                    b.ToTable("PartidoUsuario", (string)null);
                });

            modelBuilder.Entity("FutbolYa.WebAPI.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CanchaId")
                        .HasColumnType("int");

                    b.Property<string>("ClienteEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("EsFrecuente")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SedeConfirmoTransferencia")
                        .HasColumnType("bit");

                    b.Property<int>("UsuarioEstablecimientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.HasIndex("UsuarioEstablecimientoId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("FutbolYa.WebAPI.Models.ReservaUsuario", b =>
                {
                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ReservaId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ReservaUsuarios");
                });

            modelBuilder.Entity("FutbolYa.WebAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Contraseña");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailConfirmToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailConfirmTokenExpira")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("bit");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizadorId")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizadorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("Rendimientos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Actitud")
                        .HasColumnType("int");

                    b.Property<int>("Defensa")
                        .HasColumnType("int");

                    b.Property<int>("EvaluadoId")
                        .HasColumnType("int");

                    b.Property<int>("EvaluadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<int>("Pase")
                        .HasColumnType("int");

                    b.Property<int>("Puntualidad")
                        .HasColumnType("int");

                    b.Property<int>("TrabajoEquipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvaluadoId");

                    b.HasIndex("EvaluadorId");

                    b.HasIndex("PartidoId");

                    b.ToTable("Rendimientos");
                });

            modelBuilder.Entity("Calificacion", b =>
                {
                    b.HasOne("FutbolYa.WebAPI.Models.Usuario", "Evaluado")
                        .WithMany()
                        .HasForeignKey("EvaluadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FutbolYa.WebAPI.Models.Usuario", "Evaluador")
                        .WithMany()
                        .HasForeignKey("EvaluadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluado");

                    b.Navigation("Evaluador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("FutbolYa.WebAPI.Models.Cancha", b =>
                {
                    b.HasOne("FutbolYa.WebAPI.Models.Usuario", "UsuarioEstablecimiento")
                        .WithMany("Canchas")
                        .HasForeignKey("UsuarioEstablecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioEstablecimiento");
                });

            modelBuilder.Entity("FutbolYa.WebAPI.Models.DatosTarjeta", b =>
                {
                    b.HasOne("FutbolYa.WebAPI.Models.Reserva", "Reserva")
                        .WithMany("DatosTarjetas")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("FutbolYa.WebAPI.Models.Mensaje", b =>
                {
                    b.HasOne("Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutbolYa.WebAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FutbolYa.WebAPI.Models.PartidoUsuario", b =>
                {
                    b.HasOne("FutbolYa.WebAPI.Models.Usuario", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Partido", "Partido")
                        .WithMany("Jugadores")
                        .HasForeignKey("PartidosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("FutbolYa.WebAPI.Models.Reserva", b =>
                {
                    b.HasOne("FutbolYa.WebAPI.Models.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutbolYa.WebAPI.Models.Usuario", "UsuarioEstablecimiento")
                        .WithMany()
                        .HasForeignKey("UsuarioEstablecimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("UsuarioEstablecimiento");
                });

            modelBuilder.Entity("FutbolYa.WebAPI.Models.ReservaUsuario", b =>
                {
                    b.HasOne("FutbolYa.WebAPI.Models.Reserva", "Reserva")
                        .WithMany("Jugadores")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutbolYa.WebAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Partido", b =>
                {
                    b.HasOne("FutbolYa.WebAPI.Models.Usuario", "Organizador")
                        .WithMany()
                        .HasForeignKey("OrganizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FutbolYa.WebAPI.Models.Usuario", null)
                        .WithMany("Partidos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Organizador");
                });

            modelBuilder.Entity("Rendimientos", b =>
                {
                    b.HasOne("FutbolYa.WebAPI.Models.Usuario", "Evaluado")
                        .WithMany()
                        .HasForeignKey("EvaluadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FutbolYa.WebAPI.Models.Usuario", "Evaluador")
                        .WithMany()
                        .HasForeignKey("EvaluadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluado");

                    b.Navigation("Evaluador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("FutbolYa.WebAPI.Models.Reserva", b =>
                {
                    b.Navigation("DatosTarjetas");

                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("FutbolYa.WebAPI.Models.Usuario", b =>
                {
                    b.Navigation("Canchas");

                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("Partido", b =>
                {
                    b.Navigation("Jugadores");
                });
#pragma warning restore 612, 618
        }
    }
}
